-- https://en.wikibooks.org/wiki/SQL_Exercises/Movie_theatres
-- 4.1 Select the title of all movies.
-- 4.2 Show all the distinct ratings in the database.
-- 4.3  Show all unrated movies.
-- 4.4 Select all movie theaters that are not currently showing a movie.
-- 4.5 Select all data from all movie theaters 
    -- and, additionally, the data from the movie that is being shown in the theater (if one is being shown).
-- 4.6 Select all data from all movies and, if that movie is being shown in a theater, show the data from the theater.
-- 4.7 Show the titles of movies not currently being shown in any theaters.
-- 4.8 Add the unrated movie "One, Two, Three".
-- 4.9 Set the rating of all unrated movies to "G".
-- 4.10 Remove movie theaters projecting movies rated "NC-17".
